### ISSUE TITLE
Unselecting doesn't work when using deepSelect: true on a line element

### ISSUE THREAD

**Issue by dhardtke** [Fuzzyma/svg.select.js#2]
Hey,

thanks for your amazing svg.js plugin. I am currently building an SVG editor using it.

The title says it all.. here's a JSFiddle:

http://jsfiddle.net/8sdrfdun/1/

Would be great if you could have a look on this.

**Comment by Fuzzyma** [comment]
I missed that in the documentation.
You have to use `line.select(false, {deepSelect:true})` to make it work.
The function actually expects 2 Arguments. The state of the selection (true/false) and the options while the first Argument defaults to true im omitted.
You have to tell which selection to deselect because you can have both selection on one element (which doenst make that much sense but I just keep that possibility open)

**Comment by dhardtke** [comment]
Thank you, works perfectly :) +1
