### ISSUE TITLE
Drag selectRect

### ISSUE THREAD

**Issue by jkevingutierrez** [Fuzzyma/svg.select.js#20]
Hi everyone ! This is a great plugin, and I have a problem when I use with svg.draggable.js. If I try to drag an element that use select and draggable you can't drag the element.

`rect.selectize().draggable()`

Is there any way to allow the drag in the "rectSelection" to move the svg element?

**Comment by Fuzzyma** [comment]
Actually there is no pro let with dragging the element. Just make sure, that you set the right `pointer-events` in the css file. Have a look at svg.select.css for this. If you don't do that, the click event is invoked on the overlaying rectangle which visualize the selection instead of the element itself

**Comment by jkevingutierrez** [comment]
@Fuzzyma Oh man excuse me ! That was the problem I have wrong the `right pointer-events` 
Thanks !!

**Comment by bpdarlyn** [comment]
Please how do you fix this? excuse me I am new in Javascript and  I have the same problem
`let rect = draw.rect(100, 100).attr({ fill: '#f06' });
      rect.selectize({
          classRect: 'svg_select_boundingRect',
          classPoints: 'svg_select_points'
      }).resize();
      rect.draggable();`

**Comment by Fuzzyma** [comment]
When you have the same problem, the same solution might work. Did you include the css file from svg.select.js?
